name: mysql1
version: 0.20.0
description: A library for connecting to and querying MySQL & MariaDB databases.
homepage: https://github.com/adamlofts/mysql1_dart

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  crypto: ^3.0.3
  logging: ^1.2.0
  pool: ^1.5.1

dev_dependencies:
  mocktail: ^0.3.0
  options_file:
    git:
      url: https://github.com/rxlabz/optionsfile
      ref: ca741d4
  test: ^1.24.4
  very_good_analysis: ^5.0.0+1
